name: newgps
description: NEW GPS vous permet de tracker vos véhicules en temps réel.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 4.0.0+126

environment:
  sdk: ">=3.0.0-218.1.beta <4.0.0"
dependencies:
  auto_size_text: ^3.0.0
  battery_indicator: ^0.1.2
  cupertino_icons: ^1.0.5
  custom_info_window: ^1.0.1
  device_info_plus: ^8.1.0
  dropdown_search: ^5.0.6
  empty_widget: ^0.0.5
  faker: ^2.1.0
  firebase_analytics: ^10.1.1
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  firebase_remote_config: ^3.0.10
  fl_chart: ^0.60.0
  flutter:
    sdk: flutter
  flutter_animarker: ^3.2.0
  flutter_animate: ^4.1.0
  flutter_app_badger: ^1.5.0
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_native_splash: ^2.2.17
  flutter_phoenix: ^1.1.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.1
  flutter_tts: ^3.6.3
  fluttertoast: ^8.1.3
  font_awesome_flutter: ^10.4.0
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_flutter: ^2.2.3
  grouped_list: ^5.1.2
  http: ^0.13.5
  image: ^4.0.15
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.0
  label_marker: ^1.0.1
  latlong2: ^0.8.1
  lazy_data_table: ^0.3.1
  loadmore: ^2.0.1
  map_launcher: ^2.5.0+1
  month_picker_dialog: ^0.4.0
  motion_toast: ^2.6.5
  open_filex: ^4.3.2
  path_provider: ^2.0.12
  permission_handler: ^10.2.0
  provider: ^6.0.5
  share_plus: ^6.3.1
  shared_preferences: ^2.0.17
  side_sheet: ^1.0.4
  signal_strength_indicator: ^0.4.1
  simple_ripple_animation: ^0.0.7
  syncfusion_flutter_gauges: ^20.4.50
  upgrader: ^6.0.1
  url_launcher: ^6.1.9
  uuid: ^3.0.7
  wave: ^0.2.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  ## use material 3
  assets:
    - assets/
    - assets/icons/
    - assets/markers/
    - fonts/
    - fonts/icons/

  fonts:
    - family: speed
      fonts:
        - asset: fonts/icons/speed.ttf
    - family: battery
      fonts:
        - asset: fonts/icons/battery.ttf
    - family: fuel
      fonts:
        - asset: fonts/icons/fuel.ttf
    - family: geozone
      fonts:
        - asset: fonts/icons/geozone.ttf
