name: newgps
description: NEW GPS vous permet de tracker vos véhicules en temps réel.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 2.0.0+120

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  auto_size_text: ^3.0.0
  battery_indicator: ^0.1.1
  cupertino_icons: ^1.0.5
  custom_info_window: ^1.0.1
  device_info_plus: ^4.0.0
  dropdown_search: ^5.0.2
  empty_widget: ^0.0.5
  faker: ^2.0.0
  firebase_analytics: ^9.3.6
  firebase_core: ^1.22.0
  firebase_messaging: ^13.0.2
  firebase_remote_config: ^2.0.18
  fl_chart: ^0.55.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.3.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_native_splash: ^2.2.10+1
  flutter_phoenix: ^1.1.0
  flutter_phone_direct_caller: ^2.1.0
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.0.3
  flutter_tts: ^3.3.3
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.2.1
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_flutter: ^2.2.2
  grouped_list: ^5.1.2
  http: ^0.13.4
  image: ^3.1.1
  intl: ^0.17.0
  label_marker: ^1.0.1
  latlong2: ^0.8.1
  lazy_data_table: ^0.3.1
  loadmore: ^2.0.1
  map_launcher: ^2.4.0
  month_picker_dialog: ^0.4.0
  open_file: ^3.2.1
  path_provider: ^2.0.8
  permission_handler: ^10.0.2
  provider: ^6.0.2
  share_plus: ^4.0.3
  shared_preferences: ^2.0.13
  side_sheet: ^1.0.2
  signal_strength_indicator: ^0.4.1
  simple_ripple_animation: ^0.0.3
  syncfusion_flutter_gauges: ^20.2.50
  timeago: ^3.2.1
  upgrader: ^4.6.1
  url_launcher: ^6.0.18
  uuid: ^3.0.6
  wave: ^0.2.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/markers/
    - fonts/
    - fonts/icons/

  fonts:
    - family: speed
      fonts:
        - asset: fonts/icons/speed.ttf
    - family: battery
      fonts:
        - asset: fonts/icons/battery.ttf
    - family: fuel
      fonts:
        - asset: fonts/icons/fuel.ttf
    - family: geozone
      fonts:
        - asset: fonts/icons/geozone.ttf
