// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYkmKTPtC2nK4YnwHlG8jvEunmKPzNLDg',
    appId: '1:202302805202:web:5d4bdb14550e2f87fbc90b',
    messagingSenderId: '202302805202',
    projectId: 'newgps-323d9',
    authDomain: 'newgps-323d9.firebaseapp.com',
    storageBucket: 'newgps-323d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSXwd4Q8Pl0RGzeJIrNjyVwjTIOpAq4B0',
    appId: '1:202302805202:android:3b57f228af546a62fbc90b',
    messagingSenderId: '202302805202',
    projectId: 'newgps-323d9',
    storageBucket: 'newgps-323d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGPhP81bui_LL9br5ZGQbOHyzcJzF9fYU',
    appId: '1:202302805202:ios:c2fac0f3d0d42e7bfbc90b',
    messagingSenderId: '202302805202',
    projectId: 'newgps-323d9',
    storageBucket: 'newgps-323d9.appspot.com',
    iosClientId: '202302805202-mpufdbfofttphlecrkqrvfpbq0t62a5t.apps.googleusercontent.com',
    iosBundleId: 'ma.newgps.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGPhP81bui_LL9br5ZGQbOHyzcJzF9fYU',
    appId: '1:202302805202:ios:9ec93e74d8e90916fbc90b',
    messagingSenderId: '202302805202',
    projectId: 'newgps-323d9',
    storageBucket: 'newgps-323d9.appspot.com',
    iosClientId: '202302805202-0g9mqs4ll03hr6b310ah8h9e386mo44k.apps.googleusercontent.com',
    iosBundleId: 'com.example.newgpsWebapp',
  );
}
